routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('login');
Route::post('/','HomeController@signin');
Route::get('/register','HomeController@register');
Route::post('/register', 'HomeController@postRegister');
Route::post('/logout', 'HomeController@postLogout');

////////////////////////////  Dashboard Routes//////////////////

Route::prefix('main')->middleware('auth')->group(function(){
	Route::get('/','DashboardController@index');

	Route::resource('customers', 'CustomersController');

	Route::resource('products','ProductController');

	Route::resource('staffs','StaffController');

	

});
Route::prefix('transaction')->middleware('auth')->group(function(){
	Route::get('/','TransactionController@index');

});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    //
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Staff;
use App\User;
class StaffController extends Controller
{
	public function index(){
		$staffs = DB::table('staff')->get();
    return view('main.staffs.index', ['staffs' => $staffs]);
	}
    

    public function store(Request $request)

    {

        $this->validate($request, [
            'name' => 'required',
            'empno' => 'required',
            'empdate' => 'required',
            'email' => 'required',
            'phone' => 'required',
            
            

        ]);
         $user=new User;
         $user->name=$request->name;
         $user->email=$request->email;
         $user->password=bcrypt('123456');
         $user->user_level=2;
         $user->save();

        // Create Staff
        $staff = new Staff;
        $staff->user_id = $user->id;
        $staff->name = $request->input('name');
        $staff->empno = $request->input('empno');
        $staff->empdate = $request->input('empdate');
        $staff->email = $request->input('email');
        $staff->phone = $request->input('phone');
        $staff->save();

        return redirect('main/staffs')
                ->with('success', 'Staff created');

    }

    public function edit($id)
    {
        $staff = Staff::find($id);
        return view('main.staffs.edit')->with('staff', $staff);
    }


    public function update(Request $request, $staff)
    {
        $this->validate($request, [
            'name' => 'required',
            'empno' => 'required',
            'empdate' => 'required',
            'email' => 'required',
            'phone' => 'required',
            
            

        ]);

        // Update Post
        $staff = Staff::find($staff);
        $staff->name = $request->input('name');
        $staff->empno = $request->input('empno');
        $staff->empdate = $request->input('empdate');
        $staff->email = $request->input('email');
        $staff->phone = $request->input('phone');
        $staff->save();

        return redirect('main/staffs')->with('success', 'Staff Updated');
    }


    public function destroy($id)
    {
        $staff = Staff::find($id);
        $staff->delete();

        return redirect('main/staffs')->with('success', 'Staff Removed');
    }


}

resources/views/main/staffs/edit.blade.php
@extends('layouts.master')
@section('crumbs')
 <li class="breadcrumb-item">
          <a href="{{url('/main')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{url('/main/staffs')}}">Staffs</a>
        </li>
        <li class="breadcrumb-item active">Edit Staffs</li>
@endsection
@section('content')
<section class="content">   

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit Staff</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('staffs.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    <form action="{{ route('staffs.update',$staff->id) }}" method="POST">

        @csrf

        @method('PUT')
<div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $staff->name }}">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Emp_Number:</strong>

                                                <input type="text" name="empno" class="form-control" placeholder="Employment Number" value="{{ $staff->empno }}">
                                            </div>

                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Emp_Date:</strong>

                                                <input type="text" name="empdate" class="form-control" placeholder="Employment Date" id="datepicker" width="276" value="{{ $staff->empdate }}">
                                            </div>

                                        </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Email:</strong>

                    <input type="email" name="email" class="form-control" placeholder="Email" value="{{ $staff->email }}">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Phone:</strong>

                   <input type="text" name="phone" class="form-control" placeholder="Phone" value="{{ $staff->phone }}">

                </div>

            </div>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                    <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>


    </form>

    @endsection

resources/views/main/staffs/index.blade.php
@extends('layouts.master')
@section('crumbs')
 <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">staffs</li>
@endsection
@section('content')


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h1>Staff List</h1>
            </div>
            <div class="pull-right">
                <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                      Create New Staff
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                                <form method="post" action="{{ route('staffs.store')}} ">

                                    @csrf


                                     <div class="row">

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Name:</strong>

                                                <input type="text" name="name" class="form-control" placeholder="Name">

                                            </div>

                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Emp_Number:</strong>

                                                <input type="text" name="empno" class="form-control" placeholder="Employment Number">
                                            </div>

                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Emp_Date:</strong>

                                                <input type="text" name="empdate" class="form-control" id="datepicker" placeholder="Y-m-d" width="276">
                                            </div>

                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Email:</strong>

                                                <input type="email" name="email" class="form-control" placeholder="Email">

                                            </div>

                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-md-12">

                                            <div class="form-group">

                                                <strong>Phone:</strong>

                                               <input type="text" name="phone" class="form-control" placeholder="Phone">

                                            </div>

                                        </div>


                                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                                                <button type="submit" class="btn btn-primary">Submit</button>

                                        </div>

                                    </div>


                                </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
            </div>
        </div>
    </div>
<br>

<div class="container">
	<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
              <td>#</td>
              <td>NAME</td>
              <td>EMP_NUMBER</td>
              <td>EMP_DATE</td>
              <td>EMAIL</td>
              <td>PHONE</td>
              <td >Action</td>
            </tr>
        </thead>
        <tbody>
        	@if(count($staffs) > 0)
            @foreach($staffs as $index=>$staff)
            <tr>
                <td>{{$index+1}}</td>
                <td>{{$staff->name}}</td>
                <td>{{$staff->empno}}</td>
                <td>{{$staff->empdate}}</td>
                <td>{{$staff->email}}</td>
                <td>{{$staff->phone}}</td>
                <td>
          
                    <div class="btn-group" role="group" aria-label="Basic example">
 <a href="{{action('StaffController@edit',$staff->id)}}" class="pull-left btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
 &nbsp;
<form action="{{action('StaffController@destroy', $staff->id)}}" method="POST">
                    @csrf

                    @method('DELETE')
                    <input name="_method" type="hidden" value="DELETE">
                    <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-remove"></i></button>
                    </form>
</div>
                </td>
            </tr>
            @endforeach
            @else
		<p style="color: maroon;">No staffs found!!!</p>

	
	@endif
        </tbody>
    </table>
	</div>
</div>


@endsection