routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('login');
Route::post('/','HomeController@signin');
Route::get('/register','HomeController@register');
Route::post('/register', 'HomeController@postRegister');
Route::post('/logout', 'HomeController@postLogout');

////////////////////////////  Dashboard Routes//////////////////

Route::prefix('main')->middleware('auth')->group(function(){
	Route::get('/','DashboardController@index');

	Route::resource('customers', 'CustomersController');

	Route::resource('products','ProductController');

	Route::resource('staffs','StaffController');

	

});
Route::prefix('transaction')->middleware('auth')->group(function(){
	Route::get('/','TransactionController@index');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
        /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = [

        'name', 'description', 'image'

    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
        public function index()

    {

        $products = Product::latest()->paginate(5);


        return view('main.products.index',compact('products'))

            ->with('i', (request()->input('page', 1) - 1) * 5);

    }


    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('main.products.create');

    }


    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        request()->validate([

            'name' => 'required',

            'description' => 'required',

            'image' => 'required|nullable|max:1999'

        ]);
$product = Product::create(array_merge($request->all()));
if ($request->hasFile('image')) {
      $file=$request->file('image');
        $fileName= time().'.'.$file->getClientOriginalExtension();
        $request->image->move('images/products/',$fileName);
        $product->update(['image' => $fileName]);
}

        //  // File Upload
        // if($request->hasFile('image')){
        //     // Get filename with the extension
        //     $filenameWithExt = $request->file('image')->getClientOriginalName();
        //     // Get just filename
        //     $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
        //     //Get just ext
        //     $extension = $request->file('image')->getClientOriginalExtension();
        //     // Filename to store
        //     $fileNameToStore = $filename.'_'.time().'.'.$extension;
        //     // Upload Image
        //     $path = $request->file('image')->storeAs('public/images', $fileNameToStore);

        // } else {
        //     $fileNameToStore = 'noimage.jpg';
        // }


        // Create Product
        // $product = new Product;
        // $product->name = $request->input('name');
        // $product->description = $request->input('description');
        // $product->image = $fileNameToStore;
        // $product->save();


        return redirect('main/products')
                ->with('success', 'Product Created Successfully');

    }


    /**

     * Display the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function show(Product $product)

    {

        return view('main.products.show',compact('product'));

    }


    /**

     * Show the form for editing the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function edit(Product $product)

    {

        return view('main.products.edit',compact('product'));

    }


    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, $product)

    {

         $product= Product::find($product);

        $product->update(array_merge($request->all()));
        if ($request->hasFile('image')) {
              $file=$request->file('image');
                $fileName= time().'.'.$file->getClientOriginalExtension();
                $request->image->move('images/products/',$fileName);
                $product->update(['image' => $fileName]);
        }


        return redirect('main/products')
                ->with('success', 'Product Updated Successfully');

    }


    /**

     * Remove the specified resource from storage.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function destroy(Product $product)

    {

        $product->delete();


        return redirect('main/products')
                ->with('success', 'Product Deleted Successfully');

    }
}

resources/views/main/products/create.blade.php
@extends('layouts.master')


@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Add New Product</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">

        @csrf


         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    <input type="text" name="name" class="form-control" placeholder="Name">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Description:</strong>

                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail"></textarea>

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Image:</strong>

                    <div class="form-group col-md-4">
                        <input type="file" name="image">    
                    </div>

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                    <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>


    </form>


@endsection

resources/views/main/products/edit.blade.php
@extends('layouts.master')
@section('crumbs')
 <li class="breadcrumb-item">
          <a href="{{url('/main')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{url('/main/products')}}">Products</a>
        </li>
        <li class="breadcrumb-item active">Edit Products</li>
@endsection

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit Product</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">

        @csrf

        @method('PUT')


         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Description:</strong>

                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ $product->description }}</textarea>

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Image:</strong>

                    <div class="form-group col-md-4">
                        <input type="file" name="image" value="{{ $product->image }}">    
                    </div>

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>


    </form>


@endsection

resources/views/main/products/index.blade.php
@extends('layouts.master')
@section('crumbs')
 <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Products</li>
@endsection

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>PRODUCTS</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Name</th>

            <th>Description</th>

            <th>Image</th>

            <th width="280px">Action</th>

        </tr>

        @foreach ($products as $product)

        <tr>

            <td>{{ ++$i }}</td>

            <td>{{ $product->name }}</td>

            <td>{{ $product->description }}</td>

            <td><img style="width: 150px; height: 90px;" class="img-responsive" src="{{asset('images/products/'.$product->image)}}"></td>

            <td>

                <form action="{{ route('products.destroy',$product->id) }}" method="POST">


                    <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>

                    <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>


                    @csrf

                    @method('DELETE')


   

                    <button type="submit" class="btn btn-danger">Delete</button>

                </form>

            </td>

        </tr>

        @endforeach

    </table>


    {!! $products->links() !!}


@endsection

resources/views/main/products/show.blade.php
@extends('layouts.master')


@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Product Details</h2>

            </div>

         <div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    
    <img style="width: 200px; height: 200px;" class="img-responsive" src="{{asset('images/products/'.$product->image)}}">

    <h1 class="display-4">{{ $product->name }}</h1>

    <p class="lead">{{ $product->description }}</p>

    <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
  </div>
</div>

@endsection